2014-March-07@11:16:39,658 - !ERRO! - Falha ao conectar com o banco de dados. Conexão NÃO estabelecida.
Início da mensagem de erro:
java.sql.SQLException: path to 'C:\Users\c050883\Documentos Pessoais\Desenvolvimento\workspace\mapoteca\mapoteca.db': 'C:\Users\c050883\Documentos Pessoais\Desenvolvimento\workspace\mapoteca' does not exist
	at org.sqlite.Conn.open(Conn.java:103)
	at org.sqlite.Conn.<init>(Conn.java:57)
	at org.sqlite.JDBC.createConnection(JDBC.java:77)
	at org.sqlite.JDBC.connect(JDBC.java:64)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.copel.dao.BancoDeDados.<init>(BancoDeDados.java:39)
	at com.copel.dao.ProxyDAO.carregar(ProxyDAO.java:29)
	at com.copel.sgd.bo.ContaBO.carregar(ContaBO.java:28)
	at com.copel.sgd.fachada.JanelaPrincipal.<init>(JanelaPrincipal.java:49)
	at com.copel.sgd.fachada.JanelaPrincipal$1.run(JanelaPrincipal.java:38)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Final da mensagem de erro.
